import Foundation

@main
struct RunAllTests {
    static func main() async {
        print("velun test suite")

        do {
            testRouteAutoDetect()
            testDnsSuffixParentZone()
            testDnsSuffixUniqueTargets()
            await testDnsSuffixDetectMPI()
            await testDnsSuffixDetectDenyList()
            await testDnsSuffixDetectMultipleZones()
            await testDnsSuffixDetectCaseFolding()
            await testDnsSuffixDetectNoDNSServer()
            testDnsSuffixBuildPTRQuery()
            testDnsSuffixParsePTRResponse()
            testDnsSuffixParsePTRResponseTruncated()
            testPPPFraming()
            testGPLoginXML()
            try testGPGetConfigXML()
            testGPGetConfigXMLMissingIP()
            try testFortinetConfigXML()
            testFortinetEncapHeader()
            testServerAddressBareHost()
            testServerAddressHostPort()
            testServerAddressHostPortPath()
            testServerAddressScheme()
            testServerAddressSchemePortPath()
            testServerAddressTrailingSlashNoGroup()
            testServerAddressIPv4Literal()
            testServerAddressBareIPv6Untouched()
            testServerAddressBracketedIPv6Port()
            testServerAddressBracketedIPv6NoPort()
            testServerAddressRejectsOutOfRangePort()
            testServerAddressTrimsWhitespace()
            testDomainRouteHostnameParsing()
            testDomainRouteCIDRs()
            try testSharedTunnelConfigCodable()
            try testAppliedRoutesReportCodable()
            testPartialTunnelModeRawValues()
            try testUnifiedIPCCodable()
            testPacketNATRejectsNonIPv4()
            testPacketNATSourceRewriteTCP()
            testPacketNATRoundTripTCP()
            testPacketNATNoOpSameIP()
            testPacketNATDestRewriteUDP()
            testPacketNATUDPZeroChecksumPreserved()
            testPacketNATICMPLeavesL4ChecksumAlone()
            testIPv6AddrParseAndFormat()
            testIPv6AddrBytesRoundTrip()
            testIPv6AddrClassification()
            testRoutePrefix6Masking()
            testRoutePrefix6Parse()
            testRoutingTable6LongestPrefix()
            testIPv6HeaderParse()
            testIPv6TransportHeaderWalk()
            testPacketNAT6RejectsNonIPv6()
            testPacketNAT6SourceRewriteTCP()
            testPacketNAT6RoundTrip()
            testPacketNAT6NoOpSameAddress()
            testPacketNAT6DestRewriteUDP()
            testPacketNAT6ICMPv6ChecksumIsPatched()
            testPacketNAT6NonFirstFragmentLeavesL4Alone()
            testRoutingTableLongestPrefix()
            testRoutingTableNestedAndTieBreak()
            testRoutePrefixParse()
            await testRouterOutboundDemuxAndSourceNAT()
            await testRouterOutboundDropsUnmatchedAndIPv6()
            await testRouterInboundDestNAT()
            await testRouterUpdateRoutesHotSwitch()
            await testRouterIPv6DemuxAndSourceNAT()
            await testRouterIPv6InboundDestNAT()
            await testRouterIgnoresUpstreamWithoutAssignedIPv4()
            await testRouterIPv6IgnoredWhenUpstreamHasNoV6Address()
            testFlowKeeperProbesIdleFlow()
            testFlowKeeperAnsweredStaysWarm()
            testFlowKeeperRSTsDeadFlow()
            testFlowKeeperDisconnectedNoPenalty()
            testFlowKeeperEvictsOnClose()
            testFlowKeeperRebuildResetsProbes()
            testFlowKeeperThrottlesNearCycles()
            testFlowKeeperFlushAsDead()
            testFlowKeeperRetransmitsDontShieldZombie()
            testFlowKeeperVerifyModeFastVerdict()
            testFlowKeeperScopesByProfile()
            testDNSProxyQueryName()
            testDNSProxyRoute()
            testDNSProxyServfail()
            testAnyConnectFormParsing()
            await testHTTPReaderContentLength()
            await testHTTPReaderKeepAliveTwoResponses()
            await testHTTPReaderSetCookie()
            await testHTTPReaderConnectionClose()
            await testHTTPReaderCloseDelimitedBody()
            await testHTTPReaderChunked()
            await testHTTPReaderSplitAcrossReads()
            await testHTTPReaderTruncatedHeadersThrows()
            testXMLPostInitRequest()
            testXMLPostInitNoGroup()
            testXMLPostAuthReplyEchoesOpaqueAndFields()
            testXMLPostAuthReplyNoOpaqueNoSecondary()
            testXMLPostSSOAuthReply()
            testXMLPostEscaping()
            testXMLPostExtractOpaque()
            testXMLPostParsesConfigAuthResponse()
            testTOTP()
            testTOTPBase32Permissiveness()
            testBase32Encode()
            testOTPAuthURLParse()
            testMigrationSingleAccount()
            testMigrationMultipleAccounts()
            testMigrationMalformed()
            testMigrationURLSafeBase64()
            testReconnectPolicyBackoffSchedule()
            testReconnectPolicyZeroAttemptsRejected()
            await testReconnectControllerFirstTrySuccess()
            await testReconnectControllerSucceedsAfterTransientFailures()
            await testReconnectControllerExhaustsAndCarriesLastError()
            await testReconnectControllerSleepScheduleAppliedBetweenRetriesOnly()
            await testReconnectControllerClampsZeroMaxAttemptsToOne()
            testCSTPResumeRequestIncludesCookieAndReconnectHeader()
            testCSTPInitialRequestOmitsReconnectHeader()
            testCSTPRequestsIPv4First()
            try testCSTPParsesDualStackResponse()
            testCSTPRejectsIPv6OnlySession()
            try testCSTPClassifiesLegacyAddressByFamily()
            try testCSTPMalformedIPv6IsDropped()
            try testCSTPFiltersIPv6Resolvers()
            testDTLSPRFKnownAnswerSHA256()
            testDTLSPRFKnownAnswerSHA384()
            testDTLSCipherSuiteMapping()
            testDTLSKeyBlockSplit()
            testDTLSRecordRoundTrip()
            testDTLSRecordHeaderLayout()
            testDTLSHandshakeFraming()
            testDTLSClientHelloBody()
            testDTLSServerHelloParse()
            testDTLSHelloVerifyCookieParse()
            testDTLSTranscriptAndFinishedWiring()
            testDTLSHexCoding()
            testIPv4HeaderParseRejectsShort()
            testIPv4HeaderParsesMinimalHeader()
            testTCPSegmentParseRejectsShort()
            testTCPSegmentParsesSYNWithMSS()
            testTCPSegmentParsesPayload()
            testPacketBuilderProducesParseableSYN()
            testPacketBuilderRoundTripsPayload()
            testIPChecksumIsZeroWhenComputedOverFullHeader()
            testIPv4StringRoundTrip()
            testTCPOpenSendsSYN()
            testTCPSynAckCompletesHandshake()
            testTCPSendBuffersUntilEstablished()
            testTCPSendFlushesAfterEstablished()
            testTCPReceivedDataDeliveredInOrder()
            testTCPCloseSendsFINInEstablished()
            testTCPPeerFINTransitionsToCloseWait()
            testTCPRSTTearsDown()
        } catch {
            print("UNCAUGHT ERROR during suite: \(error)")
            exit(2)
        }

        exit(R.report())
    }
}
